[package]
name = "ps4-mitm"
version = "0.1.0"
edition = "2024"

[dependencies]
smoltcp = { version = "0.12", features = ["std", "medium-ethernet", "proto-ipv4", "proto-dhcpv4", "socket-tcp", "socket-udp", "socket-dns", "log"] }
rustls = "0.23"
rustls-pemfile = "2"
rcgen = "0.13"
webpki-roots = "0.26"
log = "0.4"
env_logger = "0.11"
